
export const purchaseCategories = {
    OTHER: 'Other',
    DONATIONS: 'Donations',
    AMAZON: 'Amazon',
    RESTAURANTS: 'Restaurants',
    UTILITIES: 'Utility',
    PETS: 'Pets',
    CAR: 'Car',
    HOBBIES: 'Hobbie',
    SUBSCRIPTIONS: 'Subscription',
    MEDICAL: 'Medical/Dental',
    ENTERTAINMENT: 'Entertainment',
    GAS: 'Gas',
    STORES: 'Store',
    EDUCATION: 'Education',
    GROCERIES: 'Groceries',
}

export const ItemName = {
    'QFC': purchaseCategories.GROCERIES,
    'ALBERTSONS': purchaseCategories.GROCERIES,
    'SAFEWAY': purchaseCategories.GROCERIES,
    'FRED-MEYER': purchaseCategories.GROCERIES,
    'SAFECO': purchaseCategories.ENTERTAINMENT,
    'REI': purchaseCategories.STORES,
    'ALPHA': purchaseCategories.SUBSCRIPTIONS,
    'Amazon': purchaseCategories.AMAZON,
    'AMZN': purchaseCategories.AMAZON,
    'APL*ITUNES': purchaseCategories.SUBSCRIPTIONS,
    'APPLE': purchaseCategories.SUBSCRIPTIONS,
    'ASIAN FOOD': purchaseCategories.GROCERIES,
    'AT&T': purchaseCategories.UTILITIES,
    'BARNES & NOBLE': purchaseCategories.STORES,
    'BLIZZARD': purchaseCategories.SUBSCRIPTIONS,
    'CHEVRON': purchaseCategories.GAS,
    'CHI MAC': purchaseCategories.RESTAURANTS,
    'COMCAST': purchaseCategories.UTILITIES,
    'CPR': purchaseCategories.HOBBIES,
    'DAHLIA': purchaseCategories.RESTAURANTS,
    "DICK'S": purchaseCategories.RESTAURANTS,
    'DIGITALEXTREMES': purchaseCategories.SUBSCRIPTIONS,
    'CHUPACABRA': purchaseCategories.RESTAURANTS,
    'PUB': purchaseCategories.RESTAURANTS,
    'EPULO': purchaseCategories.RESTAURANTS,
    'EUROPEAN': purchaseCategories.GROCERIES,
    'FEDEX': purchaseCategories.STORES,
    'FLO': purchaseCategories.RESTAURANTS,
    'POKE': purchaseCategories.RESTAURANTS,
    'CCP': purchaseCategories.SUBSCRIPTIONS,
    'GITHUB': purchaseCategories.SUBSCRIPTIONS,
    'GRAZIE': purchaseCategories.RESTAURANTS,
    'HOME REMEDY': purchaseCategories.STORES,
    'CALLTOPARK': purchaseCategories.CAR,
    'KAFFEEKLATSCH': purchaseCategories.RESTAURANTS,
    'OBEGI': purchaseCategories.PETS,
    'KING CO': purchaseCategories.UTILITIES,
    'CABANA': purchaseCategories.RESTAURANTS,
    'CARTA': purchaseCategories.RESTAURANTS,
    'LAKOMKA': purchaseCategories.RESTAURANTS,
    'MASALA': purchaseCategories.RESTAURANTS,
    'MERCER ST GARAGE': purchaseCategories.CAR,
    'Military1st': purchaseCategories.HOBBIES,
    'MOD PIZZA': purchaseCategories.RESTAURANTS,
    'MOON S KITCHEN': purchaseCategories.RESTAURANTS,
    'MUD BAY': purchaseCategories.PETS,
    'Netflix': purchaseCategories.SUBSCRIPTIONS,
    'NETFLIX': purchaseCategories.SUBSCRIPTIONS,
    'NORTHLAKE': purchaseCategories.RESTAURANTS,
    'PAW': purchaseCategories.PETS,
    'PET PROS': purchaseCategories.PETS,
    'PETCO': purchaseCategories.PETS,
    'PLANNED PARENTHOOD': purchaseCategories.DONATIONS,
    'PROGRESSIVE': purchaseCategories.CAR,
    'THORNTON': purchaseCategories.ENTERTAINMENT,
    'ROSS': purchaseCategories.STORES,
    'RPNW SEATTLE': purchaseCategories.GAS,
    'RUDYS': purchaseCategories.STORES,
    'SAFETY FIRST': purchaseCategories.CAR,
    'SCOTT': purchaseCategories.RESTAURANTS,
    'CITY LIGHT': purchaseCategories.UTILITIES,
    'METER PARKING': purchaseCategories.CAR,
    'SHOWBOX': purchaseCategories.ENTERTAINMENT,
    'CHAIYO': purchaseCategories.RESTAURANTS,
    'WISHES': purchaseCategories.DONATIONS,
    'ALLEGRO': purchaseCategories.RESTAURANTS,
    'STARBUCKS': purchaseCategories.RESTAURANTS,
    'TARGET': purchaseCategories.STORES,
    'TENGU': purchaseCategories.RESTAURANTS,
    'TERIYAKI': purchaseCategories.RESTAURANTS,
    'AVID ANGLER': purchaseCategories.STORES,
    'TOP POT': purchaseCategories.RESTAURANTS,
    'TOTAL WINE': purchaseCategories.STORES,
    'KIGO KITCHEN': purchaseCategories.RESTAURANTS,
    'RED MILL': purchaseCategories.RESTAURANTS,
    'STAPLE & FANCY': purchaseCategories.RESTAURANTS,
    'TWEEDY AND POPP': purchaseCategories.STORES,
    'UDEMY': purchaseCategories.EDUCATION,
    'UPPER BAR': purchaseCategories.RESTAURANTS,
    'KUOW': purchaseCategories.DONATIONS,
    'VEHICLE LICENSING ': purchaseCategories.CAR,
    'WALGREENS': purchaseCategories.STORES,
    'IZAKAYA': purchaseCategories.RESTAURANTS,
    'WEDGWOOD BROILER ': purchaseCategories.RESTAURANTS,
    'WHOLEFDS': purchaseCategories.GROCERIES,
    'WNYC': purchaseCategories.DONATIONS,
    'ZOO': purchaseCategories.ENTERTAINMENT,
    'SALOON': purchaseCategories.RESTAURANTS,
    'PAYPAL': purchaseCategories.ENTERTAINMENT,
    'CTRL MKT': purchaseCategories.GROCERIES,
    'CREATOR': purchaseCategories.STORES,
    'USGS': purchaseCategories.HOBBIES,
}

